name: example1-workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["trigger"]
    types: [requested]
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - .github/workflows/example1.yml
      - example1/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/example1.yml
      - example1/**

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a one-line script
        run: echo "x|$GITHUB_ENV|${{ job.environment.name }}|x"

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Run script file
        run: .github/scripts/script-1.sh

