name: Manual test
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: math-homework.txt
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get terragrunt binary file
        shell: bash
        run: |
          mkdir -p localbin
          wget -q -O localbin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.32.4/terragrunt_linux_amd64
          chmod +x localbin/terragrunt
          ls -la
        with:
          name: binfiles
          path: localbin
          retention-days: 1
  command:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run terragrunt version
        run: |
          export PATH="localbin:$PATH"
          terragrunt --version
          ls -la
        with:
          name: binfiles
          path: localbin


