name: Manual test
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - shell: bash
        run: |
          mkdir binfiles
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: shared_directory
          path: binfiles
