name: Manual test
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  build:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - shell: bash
        run: |
          mkdir binfiles
          curl -o binfiles/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.32.4/terragrunt_linux_amd64
          chmod +x binfiles/terragrunt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: shared_dir
          path: binfiles

  command:
    name: Deploy to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name:  Run terragrunt version
        uses: actions/download-artifact@v3
        with:
          name: shared_dir
      - shell: bash
        run: |
          ls -la
          ls -la binfiles
