name: trigger

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Manually trigger jobs'
        required: false
        default: false
  push:
    branches:
      - main
    paths:
      - .github/trigger/trigger.yml
      - trigger/**
  pull_request:
    branches:
      - main
    paths:
      - .github/trigger/trigger.yml
      - trigger/**


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: gh workflow run example1-workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}

      - name: Run script file
        run: .github/scripts/trigger.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
